### ISSUE TITLE
Improve the UI of NewBill Activity

### ISSUE THREAD

**Issue by sushant-iit** [Synergise-IIT-Bhubaneswar/QuickBills#1]
**Is your feature request related to a problem? Please describe.**
Currently, in the [NewBillActivity](../blob/master/markdown_resources/NewBillActivity.jpeg), when you create a bill with the amount in the orders of 10<sup>8</sup> or if the customer's name/address is too long, both these fields overlaps causing bad visual experience.

**Describe the solution you'd like**
Revamp the UI such that this problem is resolved. Any other improvements (like making it more cleaner) in this UI is also welcome.

**Describe alternatives you've considered**
N. A.

**Additional context**
This is the issue I'm trying to point out:

<img src = "https://user-images.githubusercontent.com/59964272/136895331-9873fd9c-0ff0-4b04-bc5f-1bb12cb59265.jpeg" height="400px" width="200px" />

**Comment by Shashwat545** [comment]
@sushant-iit I would like to work on this issue

**Comment by sushant-iit** [comment]
@Shashwat545 Go ahead
