### ISSUE TITLE
Add condition to show "Forgot Password" option

### ISSUE THREAD

**Issue by sushant-iit** [Synergise-IIT-Bhubaneswar/QuickBills#5]
**Is your feature request related to a problem? Please describe.**
It is not a problem. Currently, when a user tries to login using the email address, and if that email address is not registered / the password is incorrect, the login screen shows the option of forgot password. 

**Describe the solution you'd like**
Modify the auth.signInWithEmailAndPassword(userEmail, userPassword) function so that it does show "Forgot Password" option when the email is registered but password is incorrect and does not show "Forgot Password" when the email itself is not registered.

**Describe alternatives you've considered**
N. A.

**Additional context**
I would not want user to show "Forgot Password" option when he is not registered with the App.
The highlighted option should be shown only if the user is registered and password is incorrect.
![Screenshot](https://user-images.githubusercontent.com/59964272/138585011-b1cb9f61-08ad-4f8e-a351-eb01c1fc54a4.jpeg)

**Comment by jdkramhoft** [comment]
I'd like to take a look at this
