### ISSUE TITLE
Improve the UI of AllBills Activity

### ISSUE THREAD

**Issue by Shashwat545** [Synergise-IIT-Bhubaneswar/QuickBills#8]
**Is your feature request related to a problem? Please describe.**
Currently in the [AllBillsActivity](https://github.com/Synergise-IIT-Bhubaneswar/QuickBills/blob/master/markdown_resources/AllBillsActivity.jpg), when the amount of the bill is too long, then it overlaps with the name/ address text field which results in bad visual experience. 

**Describe the solution you'd like**
Revamp the UI such that this problem is resolved. One solution could be to display at most 2 digits after decimal and display the amount in exponential form in powers of 10. For example, 6.79 x 10^12. Any other solution which makes the UI cleaner and fixes the error is also welcome.

**Describe alternatives you've considered**
N/A

**Additional context**
This is the screenshot of the error:
![QuickBills Screenshot](https://user-images.githubusercontent.com/78429106/139153139-a7ad2377-e087-44f3-8495-506077c0d5ab.jpeg)

**Comment by sushant-iit** [comment]
This issue can now be easily solved by your preprocess function.
